const ZonasComunes = [
  {
    idZona: 108,
    zonasComunes: "Ascensor(es)",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 109,
    zonasComunes: "Cancha múltiple",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 110,
    zonasComunes: "Cuarto de basuras",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 111,
    zonasComunes: "Gimnasio",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 112,
    zonasComunes: "Lavandería",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 113,
    zonasComunes: "Piscina(s)",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 114,
    zonasComunes: "Portería",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 115,
    zonasComunes: "Salón comunal",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 116,
    zonasComunes: "Zonas verdes",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 117,
    zonasComunes: "Terraza/Sky Club",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 118,
    zonasComunes: "Tanque abastecimiento de agua",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 119,
    zonasComunes: "Salones especiales/Sala de juntas",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 120,
    zonasComunes: "Auditorio(s)",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 121,
    zonasComunes: "Cuarto técnico/Cuarto de gases",
    residencial: 0,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 122,
    zonasComunes: "Planta eléctrica de emergencia",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 123,
    zonasComunes: "Red contra incendios",
    residencial: 0,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 124,
    zonasComunes: "Aire acondicionado",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 125,
    zonasComunes: "Lobby/Recepción",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 128,
    zonasComunes: "Sin Definir",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 129,
    zonasComunes: "Parque Infantil",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 130,
    zonasComunes: "Shut Basuras",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 131,
    zonasComunes: "Zonas húmedas",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 132,
    zonasComunes: "Sede Social",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 133,
    zonasComunes: "Oficina Administración",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 134,
    zonasComunes: "BBQ",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 135,
    zonasComunes: "Salón de Juegos",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 136,
    zonasComunes: "Sendero de Trote",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 137,
    zonasComunes: "Bicicletero",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 138,
    zonasComunes: "Cancha de Futbol",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 139,
    zonasComunes: "Cancha Tenis",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 140,
    zonasComunes: "Bar",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 141,
    zonasComunes: "Cinema",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 142,
    zonasComunes: "Cancha Squash",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 143,
    zonasComunes: "Guardería",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 144,
    zonasComunes: "Golfito",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 145,
    zonasComunes: "Internet",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 146,
    zonasComunes: "Citofonía",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 147,
    zonasComunes: "Caldera",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 148,
    zonasComunes: "Plazoleta",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 149,
    zonasComunes: "Batería de Baños",
    residencial: 0,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 150,
    zonasComunes: "Cafeteria",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 151,
    zonasComunes: "Restaurante",
    residencial: 0,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 152,
    zonasComunes: "Cicloruta",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 153,
    zonasComunes: "Centro Cómputo",
    residencial: 0,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 154,
    zonasComunes: "Capilla",
    residencial: 0,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 155,
    zonasComunes: "Kiosco",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 156,
    zonasComunes: "Biblioteca",
    residencial: 0,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 157,
    zonasComunes: "Campo de Golf",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 158,
    zonasComunes: "Espejo de agua",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 159,
    zonasComunes: "Zona de pesca",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 160,
    zonasComunes: "Vestier",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 161,
    zonasComunes: "Balcón",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 162,
    zonasComunes: "Fuente",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 164,
    zonasComunes: "No responde",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 166,
    zonasComunes: "Área Lounge",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 167,
    zonasComunes: "Centro Cultural",
    residencial: 0,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 169,
    zonasComunes: "Conjunto cerrado",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 170,
    zonasComunes: "Cuarto de equipos",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 171,
    zonasComunes: "Depósito",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 172,
    zonasComunes: "Escaleras",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 173,
    zonasComunes: "Mini market",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 174,
    zonasComunes: "Muro de escalar",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 175,
    zonasComunes: "Sala múltiple",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 176,
    zonasComunes: "Salas de estudio",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 178,
    zonasComunes: "Salón de spa",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 179,
    zonasComunes: "Teatrino",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 180,
    zonasComunes: "Teatro",
    residencial: 0,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 181,
    zonasComunes: "Vías de acceso",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 182,
    zonasComunes: "Zona de niños",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 183,
    zonasComunes: "Zona de yoga",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 184,
    zonasComunes: "Coworking",
    residencial: 1,
    noResidencial: 1,
    selected: false,
  },
  {
    idZona: 185,
    zonasComunes: "Sauna",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
  {
    idZona: 186,
    zonasComunes: "Zona de mascotas",
    residencial: 1,
    noResidencial: 0,
    selected: false,
  },
];
const opcionesDepartamentoCiudadZona = [
  {
    nombre: "BOGOTA D.C",
    value: 0,
    ciudades: [
      {
        nombre: "BOGOTA D.C",
        zonas: [
          { nombre: "01 - MARANTA", valor: 1 },
          { nombre: "02 - MAZUREN", valor: 2 },
          { nombre: "03 - BOSQUE DE PINOS", valor: 3 },
          { nombre: "04 - CEDRO GOLF", valor: 4 },
          { nombre: "05 - CEDRITOS", valor: 5 },
          { nombre: "06 - ATABANZA", valor: 6 },
          { nombre: "07 - LA CALLEJA", valor: 7 },
          { nombre: "08 - BOSQUE MEDINA", valor: 8 },
          { nombre: "09 - LA CAROLINA", valor: 9 },
          { nombre: "10 - MULTICENTRO", valor: 10 },
          { nombre: "11: '11 - SANTA ANA", valor: 11 },
          { nombre: "12 - CHICO", valor: 12 },
          { nombre: "13 - ROSALES", valor: 13 },
          { nombre: "14 - CHAPINERO", valor: 14 },
          { nombre: "15 - TEUSAQUILLO", valor: 15 },
          {
            nombre: "16 - CHAPINERO ALTO",
            valor: 16,
          },
          { nombre: "17 - CENTRO", valor: 17 },
          { nombre: "18 - SAN FACON", valor: 18 },
          { nombre: "19 - 20 DE JULIO", valor: 19 },
          { nombre: "20 - QUIROGA", valor: 20 },
          {
            nombre: "21 - VILLA DE LOS ALPES",
            valor: 21,
          },
          { nombre: "22 - MARRUECOS", valor: 22 },
          { nombre: "23 - TUNJUELITO", valor: 23 },
          { nombre: "24 - AUTOPISTA SUR", valor: 24 },
          { nombre: "25 - AMERICAS", valor: 25 },
          { nombre: "26 - KENNEDY", valor: 26 },
          {
            nombre: "27 - CENTRAL DE ABASTOS",
            valor: 27,
          },
          {
            nombre: "28 - PRIMERO DE MAYO",
            valor: 28,
          },
          { nombre: "29 - CUNDINAMARCA", valor: 29 },
          { nombre: "30 - PABLO VI", valor: 30 },
          { nombre: "31 - MODELIA", valor: 31 },
          {
            nombre: "32 - MINUTO DE DIOS",
            valor: 32,
          },
          { nombre: "33 - METROPOLIS", valor: 33 },
          { nombre: "34 - BOCHICA", valor: 34 },
          { nombre: "35 - LOS ANDES", valor: 35 },
          { nombre: "36 - CORDOBA", valor: 36 },
          {
            nombre: "37 - COLINA CAMPESTRE",
            valor: 37,
          },
          { nombre: "38 - NIZA NORTE", valor: 38 },
          {
            nombre: "39 - COLINAS DE SUBA",
            valor: 39,
          },
          { nombre: "40 - LA CAMPIÑA", valor: 40 },
          { nombre: "41 - TIBABUYES", valor: 41 },
          { nombre: "42 - FONTIBON", valor: 42 },
          { nombre: "43 - BOSA", valor: 43 },
        ],
      },
    ],
  },
  {
    nombre: "CUNDINAMARCA",
    value: 1,
    ciudades: [
      {
        nombre: "AGUA DE DIOS",
        value: 116,
        zonas: [],
      },
      {
        nombre: "ALBÁN",
        value: 1,
        zonas: [],
      },
      {
        nombre: "ANAPOIMA",
        value: 2,
        zonas: [{ nombre: "116 - ANAPOIMA", value: 116 }],
      },
      {
        nombre: "ANOLAIMA",
        value: 3,
        zonas: [],
      },
      {
        nombre: "APULO",
        value: 4,
        zonas: [{ nombre: "68 APULO", value: 68 }],
      },
      {
        nombre: "ARBELÁEZ",
        value: 5,
        zonas: [],
      },
      {
        nombre: "BELTRÁN",
        value: 6,
        zonas: [],
      },
      {
        nombre: "BITUIMA",
        value: 7,
        zonas: [],
      },
      {
        nombre: "BOJACÁ'",
        value: 8,
        zonas: [{ nombre: "28 -BOJACA", value: 228 }],
      },
      {
        nombre: "CABRERA",
        value: 9,
        zonas: [],
      },
      {
        nombre: "CACHIPAY",
        value: 10,
        zonas: [],
      },
      {
        nombre: "CAJICÁ",
        value: 11,
        zonas: [{ nombre: "49 - CAJICA", value: 49 }],
      },
      {
        nombre: "CAPARRAPÍ",
        value: 12,
        zonas: [],
      },
      {
        nombre: "CÁQUEZA",
        value: 13,
        zonas: [],
      },
      {
        nombre: "CÁQUEZA",
        value: 14,
        zonas: [],
      },
      {
        nombre: "CHAGUANÍ",
        value: 15,
        zonas: [],
      },
      {
        nombre: "CHÍA",
        value: 16,
        zonas: [{ nombre: "54 - CHIA", value: 54 }],
      },
      {
        nombre: "CHIPAQUE",
        value: 17,
        zonas: [],
      },
      {
        nombre: "CHOACHÍ",
        value: 18,
        zonas: [],
      },
      {
        nombre: "CHOCONTÁ",
        value: 19,
        zonas: [],
      },
      {
        nombre: "COGUA",
        value: 20,
        zonas: [],
      },
      {
        nombre: "COTA",
        value: 21,
        zonas: [
          {
            nombre: "60 - COTA",
            value: 60,
          },
        ],
      },
      {
        nombre: "CUCUNUBÁ",
        value: 22,
        zonas: [],
      },
      {
        nombre: "EL COLEGIO",
        value: 23,
        zonas: [],
      },
      {
        nombre: "EL PEÑÓN",
        value: 24,
        zonas: [],
      },
      {
        nombre: "EL ROSAL",
        value: 25,
        zonas: [],
      },
      {
        nombre: "FACATATIVÁ",
        value: 26,
        zonas: [
          {
            nombre: "61 - FACATATIVA",
            value: 61,
          },
        ],
      },
      {
        nombre: "FÓMEQUE",
        value: 27,
        zonas: [],
      },
      {
        nombre: "FOSCA",
        value: 28,
        zonas: [],
      },
      {
        nombre: "FUNZA",
        value: 29,
        zonas: [
          {
            nombre: "58 - FUNZA",
            value: 58,
          },
        ],
      },
      {
        nombre: "FÚQUENE",
        value: 30,
        zonas: [],
      },
      {
        nombre: "FUSAGASUGÁ",
        value: 31,
        zonas: [
          {
            nombre: "65 - FUSA",
            value: 65,
          },
        ],
      },
      {
        nombre: "GACHALÁ",
        value: 32,
        zonas: [],
      },
      {
        nombre: "GACHANCIPÁ",
        value: 33,
        zonas: [
          {
            nombre: "230 - GACHANCIPA",
            value: 230,
          },
        ],
      },
      {
        nombre: "GACHETÁ",
        value: 34,
        zonas: [],
      },
      {
        nombre: "GAMA",
        value: 35,
        zonas: [],
      },
      {
        nombre: "GIRARDOT",
        value: 36,
        zonas: [
          {
            nombre: "229 - GIRARDOT",
            value: 229,
          },
        ],
      },
      {
        nombre: "GRANADA",
        value: 37,
        zonas: [],
      },
      {
        nombre: "GUACHETÁ",
        value: 38,
        zonas: [],
      },
      {
        nombre: "GUADUAS",
        value: 39,
        zonas: [],
      },
      {
        nombre: "GUASCA",
        value: 40,
        zonas: [],
      },
      {
        nombre: "GUATAQUÍ",
        value: 41,
        zonas: [],
      },
      {
        nombre: "GUATAVITA",
        value: 42,
        zonas: [],
      },
      {
        nombre: "GUAYABAL DE SÍQUIMA",
        value: 43,
        zonas: [],
      },
      {
        nombre: "GUAYABETAL",
        value: 44,
        zonas: [],
      },
      {
        nombre: "GUTIÉRREZ",
        value: 45,
        zonas: [],
      },
      {
        nombre: "JERUSALÉN",
        value: 46,
        zonas: [],
      },
      {
        nombre: "JUNÍN",
        value: 47,
        zonas: [],
      },
      {
        nombre: "LA CALERA",
        value: 48,
        zonas: [
          {
            nombre: "56 - LA CALERA",
            value: 56,
          },
        ],
      },
      {
        nombre: "LA MESA",
        value: 49,
        zonas: [],
      },
      {
        nombre: "LA PALMA",
        value: 50,
        zonas: [
          {
            nombre: "227 - LA MESA",
            value: 227,
          },
        ],
      },
      {
        nombre: "LA PEÑA",
        value: 51,
        zonas: [],
      },
      {
        nombre: "LA VEGA",
        value: 52,
        zonas: [
          {
            nombre: "67 - LA VEGA",
            value: 67,
          },
        ],
      },
      {
        nombre: "LENGUAZAQUE",
        value: 53,
        zonas: [],
      },
      {
        nombre: "MACHETÁ",
        value: 54,
        zonas: [],
      },
      {
        nombre: "MADRID",
        value: 55,
        zonas: [
          {
            nombre: "62 - MADRID",
            value: 62,
          },
        ],
      },
      {
        nombre: "MANTA",
        value: 56,
        zonas: [],
      },
      {
        nombre: "MEDINA",
        value: 57,
        zonas: [],
      },
      {
        nombre: "MOSQUERA",
        value: 58,
        zonas: [
          {
            nombre: "59 - MOSQUERA",
            value: 59,
          },
        ],
      },
      {
        nombre: "NARIÑO",
        value: 59,
        zonas: [],
      },
      {
        nombre: "NEMOCÓN",
        value: 60,
        zonas: [],
      },
      {
        nombre: "NILO",
        value: 61,
        zonas: [],
      },
      {
        nombre: "NIMAIMA",
        value: 62,
        zonas: [],
      },
      {
        nombre: "NOCAIMA",
        value: 63,
        zonas: [],
      },
      {
        nombre: "PACHO",
        value: 64,
        zonas: [],
      },
      {
        nombre: "PAIME",
        value: 65,
        zonas: [],
      },
      {
        nombre: "PANDI",
        value: 66,
        zonas: [],
      },
      {
        nombre: "PARATEBUENO",
        value: 67,
        zonas: [],
      },
      {
        nombre: "PASCA",
        value: 68,
        zonas: [],
      },
      {
        nombre: "PUERTO SALGAR",
        value: 69,
        zonas: [],
      },
      {
        nombre: "PULÍ",
        value: 70,
        zonas: [],
      },
      {
        nombre: "QUEBRADANEGRA",
        value: 71,
        zonas: [],
      },
      {
        nombre: "QUETAME",
        value: 72,
        zonas: [],
      },
      {
        nombre: "QUIPILE",
        value: 73,
        zonas: [],
      },
      {
        nombre: "RICAURTE",
        value: 74,
        zonas: [
          {
            nombre: "114 - RICAURTE",
            value: 114,
          },
        ],
      },
      {
        nombre: "SAN ANTONIO DEL TEQUENDAMA",
        value: 75,
        zonas: [],
      },
      {
        nombre: "SAN BERNARDO",
        value: 76,
        zonas: [],
      },
      {
        nombre: "SAN CAYETANO",
        value: 77,
        zonas: [],
      },
      {
        nombre: "SAN FRANCISCO",
        value: 78,
        zonas: [],
      },
      {
        nombre: "SAN JUAN DE RIOSECO",
        value: 79,
        zonas: [],
      },
      {
        nombre: "SASAIMA",
        value: 80,
        zonas: [],
      },
      {
        nombre: "SESQUILÉ",
        value: 81,
        zonas: [],
      },
      {
        nombre: "SIBATÉ",
        value: 82,
        zonas: [
          {
            nombre: "45 - SIBATE",
            value: 45,
          },
        ],
      },
      {
        nombre: "SILVANIA",
        value: 83,
        zonas: [],
      },
      {
        nombre: "SIMIJACA",
        value: 84,
        zonas: [],
      },
      {
        nombre: "SOACHA",
        value: 85,
        zonas: [
          {
            nombre: "44 - SOACHA",
            value: 44,
          },
        ],
      },
      {
        nombre: "SOPÓ",
        value: 86,
        zonas: [
          {
            nombre: "113 - SOPO",
            value: 113,
          },
        ],
      },
      {
        nombre: "SUBACHOQUE",
        value: 87,
        zonas: [],
      },
      {
        nombre: "SUESCA",
        value: 88,
        zonas: [],
      },
      {
        nombre: "SUPATÁ",
        value: 89,
        zonas: [],
      },
      {
        nombre: "SUSA",
        value: 90,
        zonas: [],
      },
      {
        nombre: "SUTATAUSA",
        value: 91,
        zonas: [],
      },
      {
        nombre: "TABIO",
        value: 92,
        zonas: [
          {
            nombre: "66 - TABIO",
            value: 66,
          },
        ],
      },
      {
        nombre: "TAUSA",
        value: 93,
        zonas: [],
      },
      {
        nombre: "TENA",
        value: 94,
        zonas: [],
      },
      {
        nombre: "TENJO",
        value: 95,
        zonas: [
          {
            nombre: "48 - TENJO",
            value: 48,
          },
        ],
      },
      {
        nombre: "TIBACUY",
        value: 96,
        zonas: [],
      },
      {
        nombre: "TIBIRITA",
        value: 97,
        zonas: [],
      },
      {
        nombre: "TOCAIMA",
        value: 98,
        zonas: [],
      },
      {
        nombre: "TOCANCIPÁ",
        value: 99,
        zonas: [
          {
            nombre: "115 - TOCANCIPÁ",
            value: 115,
          },
        ],
      },
      {
        nombre: "TOPAIPÍ",
        value: 100,
        zonas: [],
      },
      {
        nombre: "UBALÁ",
        value: 101,
        zonas: [],
      },
      {
        nombre: "UBAQUE",
        value: 102,
        zonas: [],
      },
      {
        nombre: "UNE",
        value: 103,
        zonas: [],
      },
      {
        nombre: "ÚTICA",
        value: 104,
        zonas: [],
      },
      {
        nombre: "VENECIA",
        value: 105,
        zonas: [],
      },
      {
        nombre: "VERGARA",
        value: 106,
        zonas: [],
      },
      {
        nombre: "VIANÍ",
        value: 107,
        zonas: [],
      },
      {
        nombre: "VILLA DE SAN DIEGO DE UBATÉ",
        value: 108,
        zonas: [],
      },
      {
        nombre: "VILLAGÓMEZ",
        value: 109,
        zonas: [],
      },
      {
        nombre: "VILLAPINZÓN",
        value: 110,
        zonas: [],
      },
      {
        nombre: "VILLETA",
        value: 111,
        zonas: [
          {
            nombre: "120 - VILLETA",
            value: 120,
          },
        ],
      },
      {
        nombre: "VIOTÁ",
        value: 112,
        zonas: [],
      },
      {
        nombre: "YACOPÍ",
        value: 113,
        zonas: [],
      },
      {
        nombre: "ZIPACÓN",
        value: 114,
        zonas: [],
      },
      {
        nombre: "ZIPAQUIRÁ",
        value: 115,
        zonas: [
          {
            nombre: "53 - ZIPAQUIRA",
            value: 53,
          },
        ],
      },
    ],
  },
];

const technicalFeaturesData = [
  {
    id: 1,
    categoria: "Subestructura R-NR",
    caracteristicaId: 7,
    caracteristica: "Cimentaciones",
    especificacion: {
      21: "Micropilotes",
      22: "Pilotes",
      23: "Caissons",
      24: "Zapatas",
      25: "Losas o placas de cimentación",
      26: "Placa flotada",
      78: "Estructura metálica",
      88: "No responde",
      89: "Sin definir",
      90: "Otro",
      98: "No aplica",
    },
  },
  {
    id: 1,
    categoria: "Subestructura R-NR",
    caracteristicaId: 8,
    caracteristica: "Sótanos / semisótanos",
    especificacion: {
      27: "Industrializado",
      28: "Prefabricados",
      29: "Mamposteria confinada",
      91: "No responde",
      92: "Sin definir",
      93: "Otro",
      99: "No aplica",
    },
  },
  {
    id: 2,
    categoria: "Sistema Constructivo R",
    caracteristicaId: 9,
    caracteristica: "Tradicional",
    especificacion: {
      60: "Aporticado",
    },
  },
  {
    id: 2,
    categoria: "Sistema Constructivo R",
    caracteristicaId: 10,
    caracteristica: "Mampostería Estructural",
    especificacion: {
      31: "Mampostería Estructural",
      109: "Estructura combinada",
    },
  },
  {
    id: 2,
    categoria: "Sistema Constructivo R",
    caracteristicaId: 11,
    caracteristica: "Industrializado",
    especificacion: {
      32: "Forsa",
      33: "Contech",
      34: "Outinord",
      35: "Unispan",
      36: "Otro tipo de formaleta metálica",
      37: "Sin definir",
      79: "Manoportable",
      80: "Tunel",
      84: "No responde",
      85: "Otro",
      100: "No aplica",
    },
  },
  {
    id: 2,
    categoria: "Sistema Constructivo R",
    caracteristicaId: 12,
    caracteristica: "Estructura metálica",
    especificacion: {
      38: "Estructura metálica",
    },
  },
  {
    id: 3,
    categoria: "Placa entre piso R",
    caracteristicaId: 13,
    caracteristica: "Placa entre Piso",
    especificacion: {
      39: "Aligerada con casetón",
      40: "Aligerada con icopor",
      41: "Aligerada Retcell",
      42: "Bloquelón",
      43: "Placa con steel deck",
      44: "Placa o losa maciza",
      45: "No responde",
      46: "Sin Definir",
      47: "Otro",
      101: "No aplica",
      107: "Aligerada con Poliestireno",
    },
  },
  {
    id: 4,
    categoria: "Divisiones interiores R-NR",
    caracteristicaId: 14,
    caracteristica: "Divisiones interiores",
    especificacion: {
      48: "Bloque arcilla",
      49: "Bloque hormigón",
      50: "Concreto",
      51: "Dry wall",
      52: "Durapanel",
      54: "Ladrillo de arcilla",
      55: "Ladrillo de hormigon",
      56: "Super board",
      57: "No responde",
      58: "Sin Definir",
      59: "Otro",
      81: "Placa Board",
      96: "No aplica",
      104: "Vidrio",
    },
  },
  {
    id: 5,
    categoria: "Sistema Constructivo NR",
    caracteristicaId: 15,
    caracteristica: "Tradicional",
    especificacion: {
      60: "Aporticado",
    },
  },
  {
    id: 5,
    categoria: "Sistema Constructivo NR",
    caracteristicaId: 16,
    caracteristica: "Mampostería Estructural",
    especificacion: {
      61: "Mampostería Estructural ",
    },
  },
  {
    id: 5,
    categoria: "Sistema Constructivo NR",
    caracteristicaId: 17,
    caracteristica: "Industrializado",
    especificacion: {
      62: "Forsa",
      63: "Contech",
      64: "Outinord",
      65: "Unispan",
      66: "Otro tipo de formaleta metálica",
      67: "Sin definir",
      82: "Manoportable",
      83: "Tunel",
      86: "No responde",
      87: "Otro",
      95: "No aplica",
    },
  },
  {
    id: 5,
    categoria: "Sistema Constructivo NR",
    caracteristicaId: 18,
    caracteristica: "Estructura metálica",
    especificacion: {
      68: "Estructura metálica",
    },
  },
  {
    id: 5,
    categoria: "Sistema Constructivo NR",
    caracteristicaId: 19,
    caracteristica: "Estructura combinada (concreto con metál)",
    especificacion: {
      69: "Estructura combinada",
      102: "No aplica",
      103: "Sin definir",
    },
  },
  {
    id: 6,
    categoria: "Placa entre piso NR",
    caracteristicaId: 20,
    caracteristica: "Placa entre Piso",
    especificacion: {
      70: "Aligerada con casetón",
      71: "Aligerada con icopor",
      72: "Aligerada Retcell",
      73: "Placa con steel deck",
      74: "Placa o losa maciza",
      75: "No responde",
      76: "Sin Definir",
      77: "Otro",
      94: "No aplica",
    },
  },
];

const exteriorFinishDataStage = [
  {
    id: 53,
    nombre: "Muebles cocina R",
    residencial: {
      69: "Acero inoxidable",
      70: "Aglomerado",
      71: "Madecor/melamínico",
      72: "Madera",
      73: "Termolaminado",
      74: "No responde",
      75: "No aplica",
      76: "Otro",
      381: "Sin definir",
      393: "Formica",
    },
    noResidencial: [],
  },
  {
    id: 54,
    nombre: "Mesón cocina R",
    residencial: {
      77: "Acero inoxidable",
      78: "Concreto",
      79: "Granito",
      80: "Madera",
      81: "Mármol",
      82: "Policuarzo",
      83: "Porcelanato",
      84: "No responde",
      85: "No aplica",
      86: "Otro",
      380: "Sin definir",
      416: "Quarztone",
    },
    noResidencial: [],
  },
  {
    id: 55,
    nombre: "Lavadero R",
    residencial: {
      87: "Concreto",
      88: "Fibra de vidrio",
      89: "Granito",
      90: "No responde",
      91: "No aplica",
      92: "Otro",
      378: "Sin definir",
      382: "Policuarzo",
    },
    noResidencial: [],
  },
  {
    id: 56,
    nombre: "Muros alcobas R",
    residencial: {
      93: "Caraplast",
      94: "Pañetados",
      95: "Pañetados, estucados y pintados",
      96: "Pañetados y pintados ",
      97: "Sin pañetar y sin pintar",
      98: "Dry Wall",
      99: "Ladrillo a la vista",
      100: "Papel colgadura",
      101: "No responde",
      102: "No aplica",
      103: "Otro",
      223: "Concreto a la vista",
      224: "Pañetado y estucado",
      379: "Sin definir",
    },
    noResidencial: [],
  },
  {
    id: 57,
    nombre: "Muros cocina R",
    residencial: {
      104: "Caraplast",
      105: "Pañetados",
      106: "Pañetados, estucados y pintados",
      107: "Pañetados y pintados ",
      108: "Sin pañetar y sin pintar",
      109: "No responde",
      110: "No aplica",
      111: "Otro",
      219: "Cerámica",
      220: "Porcelanato",
      221: "Ladrillo a la vista",
      222: "Granito",
      230: "Pañete, estuco",
      377: "Sin definir",
      395: "Concreto a la vista",
    },
    noResidencial: [],
  },
  {
    id: 58,
    nombre: "Cielo raso alcobas R",
    residencial: {
      112: "Caraplast",
      113: "Drywall",
      114: "Madera machiembrada",
      115: "Pañetados",
      116: "Pañetados, estucados y pintados",
      117: "Pañetados y pintados ",
      118: "Teja a la vista",
      119: "No responde",
      120: "No aplica",
      121: "Otro",
      218: "Pañetado y estucado",
      376: "Sin definir",
      383: "Placa concreto a la vista",
      384: "PVC",
      385: "Bloquelon",
    },
    noResidencial: [],
  },
  {
    id: 59,
    nombre: "Cielo raso baños R",
    residencial: {
      122: "Caraplast",
      123: "Drywall",
      124: "Pañete, estuco",
      125: "Pañete, estuco, pintura",
      126: "Pañete, pintura",
      127: "Teja a la vista",
      128: "No responde",
      129: "No aplica",
      130: "Otro",
      215: "Cerámica",
      216: "Pañete",
      217: "Madera machiembrada ",
      375: "Sin definir",
      386: "Placa concreto a la vista",
      387: "PVC",
      388: "Bloquelon",
    },
    noResidencial: [],
  },
  {
    id: 60,
    nombre: "Cielo raso cocina R",
    residencial: {
      131: "Acrílico",
      132: "Caraplast",
      133: "Drywall",
      134: "Madera machiembrada",
      135: "Pañete, estuco",
      136: "Pañete, estuco, pintura",
      137: "Pañete, pintura",
      138: "Teja a la vista",
      139: "No responde",
      140: "No aplica",
      141: "Otro",
      229: "Pañete",
      374: "Sin definir",
      389: "Placa concreto a la vista",
      390: "PVC",
      391: "Bloquelon",
    },
    noResidencial: [],
  },
  {
    id: 61,
    nombre: "Piso alcobas R",
    residencial: {
      142: "Alfombra",
      143: "Caucho",
      144: "Cerámica",
      145: "Granito",
      146: "Laminado madera",
      147: "Madera",
      148: "Mármol",
      149: "Piso afinado",
      150: "Porcelanato",
      151: "No responde",
      152: "No aplica",
      153: "Otro",
      373: "Sin definir",
      401: "Vinilico",
      415: "PVC / caucho",
    },
    noResidencial: [],
  },
  {
    id: 62,
    nombre: "Muros habitaciones NR",
    residencial: [],
    noResidencial: {
      154: "Caraplast",
      155: "Pañetados",
      156: "Pañetados, estucados y pintados",
      157: "Pañetados y pintados",
      158: "Sin pañetar y sin pintar",
      159: "Dry Wall",
      160: "Ladrillo a la vista",
      161: "Papel colgadura",
      162: "No responde",
      163: "No aplica",
      164: "Otro",
      372: "Sin definir",
    },
  },
  {
    id: 63,
    nombre: "Cielo raso habitaciones NR",
    residencial: [],
    noResidencial: {
      165: "Caraplast",
      166: "Drywall",
      167: "Madera machiembrada",
      168: "Pañetados",
      169: "Pañetados, estucados y pintados",
      170: "Pañetados y pintados ",
      171: "Teja a la vista",
      172: "No responde",
      173: "No aplica",
      174: "Otro",
      371: "Sin definir",
    },
  },
  {
    id: 65,
    nombre: "Piso habitaciones NR",
    residencial: [],
    noResidencial: {
      183: "Alfombra",
      184: "Caucho",
      185: "Cerámica",
      186: "Granito",
      187: "Laminado madera",
      188: "Madera",
      189: "Mármol",
      190: "Porcelanato",
      191: "No responde",
      192: "No aplica",
      193: "Otro",
      369: "Sin definir",
    },
  },
  {
    id: 66,
    nombre: "Muros baños R - NR",
    residencial: [],
    noResidencial: {
      194: "Cerámica",
      195: "Granito",
      196: "Pañetados",
      197: "Pañetados, estucados y pintados",
      198: "Pañetados y pintados",
      199: "Sin pañetar y sin pintar",
      200: "Porcelanato",
      201: "No responde",
      202: "No aplica",
      203: "Otro",
      225: "Caraplast",
      226: "Pañetado y estucado",
      227: "Ladrillo a la vista",
      228: "Mármol",
      368: "Sin definir",
      396: "Concreto a la vista",
    },
  },
  {
    id: 67,
    nombre: "División baños R - NR",
    residencial: [],
    noResidencial: {
      204: "Acrílico",
      205: "Vidrio templado",
      206: "No responde",
      207: "No aplica",
      208: "Otro",
      367: "Sin definir",
    },
  },
  {
    id: 68,
    nombre: "Puerta Principal R - NR",
    residencial: [],
    noResidencial: {
      209: "Madera",
      210: "Metálica",
      211: "Seguridad",
      212: "No responde",
      213: "No aplica",
      214: "Otro",
      366: "Sin definir",
      398: "Vidrio",
    },
  },
  {
    id: 231,
    nombre: "Lavamanos R-NR",
    residencial: [],
    noResidencial: {
      243: "Sobreponer",
      244: "Colgar",
      245: "Pedestal",
      246: "No aplica",
      247: "No responde",
      248: "Otro",
      365: "Sin definir",
      402: "Empotrado",
    },
  },
  {
    id: 232,
    nombre: "Mesón baños R-NR",
    residencial: [],
    noResidencial: {
      249: "Marmol",
      250: "Granito",
      251: "Madera",
      252: "Cerámica",
      253: "Policuarzo",
      254: "Acero",
      255: "Piedra",
      256: "Vidrio",
      257: "Fibra de vidrio",
      258: "No aplica",
      259: "No responde",
      260: "Otro",
      364: "Sin definir",
    },
  },
  {
    id: 233,
    nombre: "Muebles lavamanos R-NR",
    residencial: [],
    noResidencial: {
      261: "Madera",
      262: "Madecor",
      263: "Melamínico",
      264: "No aplica",
      265: "No responde",
      266: "Otro",
      363: "Sin definir",
      394: "Formica",
    },
  },
  {
    id: 234,
    nombre: "Cornisa R",
    residencial: {
      267: "Yeso",
      268: "Madera",
      269: "No aplica",
      270: "No responde",
      271: "Otro",
      362: "Sin definir",
    },
    noResidencial: [],
  },
  {
    id: 235,
    nombre: "Closet material R",
    residencial: {
      272: "Madera",
      273: "Madecor",
      274: "Aglomerado",
      275: "Melamínico",
      276: "No aplica",
      277: "No responde",
      278: "Otro",
      361: "Sin definir",
      392: "Formica",
    },
    noResidencial: [],
  },
  {
    id: 236,
    nombre: "Dotación cocina R",
    residencial: {
      279: "Estufa",
      280: "Horno",
      281: "Campana / Extractor",
      282: "Calentador",
      283: "No aplica",
      284: "No responde",
      285: "Otro",
      360: "Sin definir",
    },
    noResidencial: [],
  },
  {
    id: 237,
    nombre: "Tipo Cocina R",
    residencial: {
      286: "Integral",
      287: "Sólo mesón",
      288: "Semi integral",
      289: "No aplica",
      290: "No responde",
      291: "Otro",
      359: "Sin definir",
    },
    noResidencial: [],
  },
  {
    id: 239,
    nombre: "Pisos baño NR",
    residencial: [],
    noResidencial: {
      299: "Cerámica",
      300: "Porcelanato",
      301: "Cemento afinado",
      302: "Mármol",
      303: "No aplica",
      304: "No responde",
      305: "Otro",
      357: "Sin definir",
    },
  },
  {
    id: 240,
    nombre: "Pisos cocina R",
    residencial: {
      306: "Cerámica",
      307: "Porcelanato",
      308: "Cemento afinado",
      309: "Granito",
      310: "Madera",
      311: "Mármol",
      312: "No aplica",
      313: "No responde",
      314: "Otro",
      356: "Sin definir",
      397: "PVC / Caucho",
      399: "Vinilico",
    },
    noResidencial: [],
  },
  {
    id: 241,
    nombre: "Puertas interiores R",
    residencial: {
      315: "Madera",
      316: "Madecor",
      317: "Aglomerado",
      318: "Melaminico",
      319: "Metálica",
      320: "No aplica",
      321: "No responde",
      322: "Otro",
      355: "Sin definir",
    },
    noResidencial: [],
  },
  {
    id: 242,
    nombre: "Puertas ubicación R",
    residencial: {
      323: "Todas",
      324: "En una alcoba, en un baño",
      325: "Baños",
      326: "Alcobas",
      327: "No aplica",
      328: "No responde",
      329: "Otro",
      354: "Sin definir",
    },
    noResidencial: [],
  },
  {
    id: 238,
    nombre: "Pisos baño R",
    residencial: {
      292: "Cerámica",
      293: "Porcelanato",
      294: "Cemento afinado",
      295: "Mármol",
      296: "No aplica",
      297: "No responde",
      298: "Otro",
      358: "Sin definir",
      400: "Vinilico",
      414: "PVC / caucho",
    },
    noResidencial: [],
  },
];

export {
  ZonasComunes,
  opcionesDepartamentoCiudadZona,
  technicalFeaturesData,
  exteriorFinishDataStage,
};
